// react/src/components/AddTodo.jsx
import React from "react";
import { useRef } from "react";

const AddTodo = ({ onAddTodo }) => {
  const todoInputRef = useRef();

  return (
    <>
      <form action="">
        <input
          type="text"
          placeholder="todo"
          id="todovalue"
          ref={todoInputRef}
        />
        <input
          type="submit"
          id="todohandler"
          onClick={() => onAddTodo(event, todoInputRef.current.value)}
        />
      </form>
    </>
  );
};

export default AddTodo;

// solidjs/src/components/AddTodo.jsx
import { createSignal } from "solid-js";

const AddTodo = ({ onAddTodo }) => {
  const [getText, setText] = createSignal("");

  return (
    <>
      <form action="">
        <input
          type="text"
          placeholder="todo"
          onInput={(e) => {
            setText(e.target.value);
          }}
        />
        <input
          type="submit"
          id="todohandler"
          onClick={() => onAddTodo(event, getText())}
        />
      </form>
    </>
  );
};

export default AddTodo;
