// react/src/components/AddTodo.jsx
import React from "react";
import { useRef } from "react";

const AddTodo = ({ onAddTodo }) => {
  const todoInputRef = useRef();

  return (
    <>
      <form action="">
        <input
          type="text"
          placeholder="todo"
          id="todovalue"
          ref={todoInputRef}
        />
        <input
          type="submit"
          id="todohandler"
          onClick={() => onAddTodo(event, todoInputRef.current.value)}
        />
      </form>
    </>
  );
};

export default AddTodo;

// angular/src/app/addtodo/addtodo.component.ts
import { Component, OnInit, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-addtodo',
  templateUrl: './addtodo.component.html',
  styleUrls: ['./addtodo.component.css'],
})
export class AddtodoComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}

  @Output() newItemEvent = new EventEmitter<string>();

  addNewItem(value: string, event: MouseEvent) {
    event.preventDefault();
    this.newItemEvent.emit(value);
  }
}

<form action="">
  <input type="text" placeholder="todo" id="todovalue" #newTodo />
  <input
    type="submit"
    id="todohandler"
    (click)="addNewItem(newTodo.value, $event)"
  />
</form>
