// vuejs/src/components/AddTodo.vue
<template>
  <form action="">
    <input type="text" placeholder="todo" id="todovalue" v-model="value" />
    <input type="submit" id="todohandler" @click.prevent="onAddTodo(value)" />
  </form>
</template>

<script setup>
import { ref } from "vue";

const value = ref("");

defineProps({
  onAddTodo: Function,
});
</script>

// react/src/components/AddTodo.jsx
import React from "react";
import { useRef } from "react";

const AddTodo = ({ onAddTodo }) => {
  const todoInputRef = useRef();

  return (
    <>
      <form action="">
        <input
          type="text"
          placeholder="todo"
          id="todovalue"
          ref={todoInputRef}
        />
        <input
          type="submit"
          id="todohandler"
          onClick={() => onAddTodo(event, todoInputRef.current.value)}
        />
      </form>
    </>
  );
};

export default AddTodo;
